name: Unit Tests
on:
  pull_request:
    branches: [main]
jobs:
  Checkout-And-Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest